version: '3.8'

services:
  app:
    container_name: jazke-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #   NODE_ENV: production
    #   PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
    # volumes:
    #   - .:/usr/src/app
    # working_dir: /usr/src/app
