version: '3.8'

services:
  app:
    container_name: jazke-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    environment:
      NODE_ENV: production
      DATABASE_URI: postgres://jazkadmin:Development.313*@jazk-postgres-fdb.postgres.database.azure.com/web_dev
      HOST: https://jazk-web-ca.victoriousriver-e1958513.northeurope.azurecontainerapps.io
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
