version: '3.8'

services:
  app:
    container_name: jazke-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    environment:
      NODE_ENV: production
      DATABASE_URI: postgres://admin:admin@143.198.68.104:5432/jazke-web
      HOST: https://jazk-web-ca.victoriousriver-e1958513.northeurope.azurecontainerapps.io
      test: 14
      # PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable
