version: '3.8'

services:
  app:
    container_name: jazke-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    environment:
      NODE_ENV: production
      DATABASE_URI: mongodb+srv://admin:6iT4wLTN6rXYa8B@cluster0.2toly.mongodb.net/debunkbot?retryWrites=true&w=majority
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
