name: Trigger auto deployment for jazk-web-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/jazk-web-ca-AutoDeployTrigger-c419ba83-9417-4b2b-a91b-9d026f91dbda.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.JAZKWEBCA_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          # appSourcePath: ${{ github.workspace }}Dockerfile
          appSourcePath: ${{ github.workspace }}
          # _dockerfilePathKey_: _dockerfilePath_
          registryUrl: jazkapiregistry.azurecr.io
          registryUsername: ${{ secrets.JAZKWEBCA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.JAZKWEBCA_REGISTRY_PASSWORD }}
          containerAppName: jazk-web-ca
          resourceGroup: jazk-api-rg
          containerAppEnvironment: jazk-api-env2
          ingress: external
          targetPort: 3100
          dockerfilePath: Dockerfile
          # imageToBuild: jazkapiregistry.azurecr.io/jazk-web-ca:${{ github.sha }}
          imageToBuild: jazkapiregistry.azurecr.io/jazk-web-ca:latest
          
            

     

